### ISSUE TITLE
Pancakeswap

### ISSUE THREAD

**Issue by rhanifrizal** [cusdt-LINK/alpha-kcc-dex-bot#3]
hello, ive setting the bot to trade on pancakeswap, however, when i run the program it keep on connecting to KCC and checking on my ALPHA balance. Where do i need to modify so that it can trade on BSC platform and using BNB to buy other tokens.

Below is the error
![www](https://user-images.githubusercontent.com/63175893/165783041-ae678015-3c07-47d3-b831-58b573051cf9.png)

Below is my setting file
![Screenshot_3ww](https://user-images.githubusercontent.com/63175893/165783248-0a989d10-35ef-4ec2-9c9d-1e223ccc693a.png)

Below is the tokens file
![Screenshot_3ww](https://user-images.githubusercontent.com/63175893/165783381-ab309961-22d0-4652-8c0c-18881becca25.png)

**Comment by benbrottslingen** [comment]
Do you have BNB in your wallet?

**Comment by Eclipz2125** [comment]
> hello, ive setting the bot to trade on pancakeswap, however, when i run the program it keep on connecting to KCC and checking on my ALPHA balance. Where do i need to modify so that it can trade on BSC platform and using BNB to buy other tokens.
> 
> Below is the error ![www](https://github.com/assets/63175893/ae678015-3c07-47d3-b831-58b573051cf9)
> 
> Below is my setting file ![Screenshot_3ww](https://github.com/assets/63175893/0a989d10-35ef-4ec2-9c9d-1e223ccc693a)
> 
> Below is the tokens file ![Screenshot_3ww](https://github.com/assets/63175893/ab309961-22d0-4652-8c0c-18881becca25)

I'm building my own front runner let me know if you are interested in collaborating
https://t.me/BuyHighSellLowQQ

**Comment by gweidart** [comment]
> hello, ive setting the bot to trade on pancakeswap, however, when i run the program it keep on connecting to KCC and checking on my ALPHA balance. Where do i need to modify so that it can trade on BSC platform and using BNB to buy other tokens.
> 
> 
> 
> 
> 
> Below is the error
> 
> ![www](https://user-images.githubusercontent.com/63175893/165783041-ae678015-3c07-47d3-b831-58b573051cf9.png)
> 
> 
> 
> Below is my setting file
> 
> ![Screenshot_3ww](https://user-images.githubusercontent.com/63175893/165783248-0a989d10-35ef-4ec2-9c9d-1e223ccc693a.png)
> 
> 
> 
> Below is the tokens file
> 
> ![Screenshot_3ww](https://user-images.githubusercontent.com/63175893/165783381-ab309961-22d0-4652-8c0c-18881becca25.png)
> 
> 
> 
> 

You will need to run the bot from source. I updated the source to NOT require you to hold any tokens to use the bot. The pre compiled version has NOT been updated nor do I have any plans to update the precompiled version at this time.

**Comment by earnbuzz** [comment]
how to change the network
