### ISSUE TITLE
Relation to Limit-Sniper?

### ISSUE THREAD

**Issue by coccoinomane** [cusdt-LINK/alpha-kcc-dex-bot#6]
Hello,
I have been playing around with your sniper bot, thanks for sharing it!

Cocco

**Comment by goheesheng** [comment]
I feel like this repo and that repo u sent is sus. Do research more about this type of scams

**Comment by goheesheng** [comment]
That repo contained pre-compiled codes which we do not know if it's malicious unless we reverse engineer it. Please be careful !

**Comment by coccoinomane** [comment]
Thanks mate for your reply! 

May I ask whether your bot is a fork of a previous one?

**Comment by goheesheng** [comment]
I did not fork it neither dare to run it without reverse engineering to check if it's legit. Please be careful using such bots!

**Comment by goheesheng** [comment]
If it's too good to be true, it's NOT!
