### ISSUE TITLE
I am not able to run this always asks for alpha tokens

### ISSUE THREAD

**Issue by mazgalesc** [cusdt-LINK/alpha-kcc-dex-bot#7]
can you please point the link to the version that has this removed

**Comment by mazgalesc** [comment]
gonna contact you on telegram

**Comment by 0xmatt1** [comment]
@mazgalesc just comment out the last few requirement conditions at the bottom of the
AlphaBot.py file 😎  than build from source.  @gweidart did change the script so it does not need the alpha token balance anymore so try building from source first without changes , and if it still nags you about that go to the bottom of that file I referenced and make the necessary code changes to make the bypass complete if it already isn't already (there's a few ways to do it)

**Comment by mazgalesc** [comment]
@0xmatt1 Oh thanks for the info will check on that. I was running it in vscode and always got the alpha requirement.
